### PR TITLE
Added basic docker file

### PR DESCRIPTION
**Pull request by eiabea**
finalized dockerfile

### CODE REVIEW

**Comment by eiabea** [comment]
@radfish sorry for all the trouble, i hope this is okay :disappointed:

**Comment by fluffypony** [comment]
@eiabea can I close #1025 in favour of this?

**Comment by eiabea** [comment]
@fluffypony yes please! :smiley:

**Comment by alexeicolin** [comment]
@eiabea Thanks. In the future please squash and `push -f` (forced push, which "overwrites" any existing commits in the branch) to the same PR branch instead of opening new PRs. That way the record associated with the PR is all in one place.

**Comment by radfish** [comment]
@eiabea Thanks. In the future please squash and `push -f` to to the same PR branch (force push, which "overwrites" any existing commits in the remote branch) instead of creating new PRs. This way all record is kept in one place.

**Pull request merged**
