### PR TITLE
Change Name to Moonero

### PR DESCRIPTION
**Pull request by BitcoinErrorLog**
I propose a name change to the project and all related uses of the word Monero to Moonero. This is an important and necessary branding change that will help ensure the success of the project. Let's be honest, we all know Monero is a weird name, and most people ignore it because it sounds Mexican. With a name like Moonero, the world can embrace this trailblazing project and give it the hype it needs to propel it to greatness.

I've done the hard work of replacing all the names in this README.md doc, the rest is up to you!

### CODE REVIEW

**Comment by lethos3** [comment]
NACK

**Comment by luigi1111** [comment]
ACK

**Comment by luigi1111** [comment]
Oh wait it's not April 1.

**Comment by fluffypony** [comment]
MACK is BACK with a brand new TRACK

**Comment by BitcoinErrorLog** [comment]
lethos3, aren't you supposed to give a reason for the NACK? 

I'm trying to give branding consultation for free here, the least you could do is explain yourself!

**Comment by lethos3** [comment]
It isn't Esperanto anymore

**Comment by anonimal** [comment]
But I like muh freedoms and Muhnero.

> When the cow says "moo", muh crypto-currency says **Muhnero**.

:wink:

**Comment by moneromooo-monero** [comment]
NAK. You forgot a o everywhere. Make it Mooonero and I'll feel happier.

**Comment by luigi1111** [comment]
moooneromooo-mooonero

**Comment by fluffypony** [comment]
Closing due to lack of tests

**Pull request closed without merging**
