### PR TITLE
rpc: add pool/blockchain and block height results to gettransactions

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by iamsmooth** [comment]
Is it a good idea to change the format of an existing response like this? 

Would that create a version dependence between the daemon and wallet that wasn't an issue before?

If so, this seems like it could be problematic for remote nodes and general interoperability.

**Comment by moneromooo-monero** [comment]
It is not a very good idea, but the alternative is to continue adding more lists/vectors for random stuff, which increase the risk of getting one out of sync. Doing this now means future additions don't break anything. I suppose I could include both now though, which would tide over anyone that might be using this RPC.

**Comment by moneromooo-monero** [comment]
The daemon now fills both old and new style data, and the wallet understands both.

**Comment by fluffypony** [comment]
Reviewed

**Pull request merged**
