### PR TITLE
Fix upstream issue#1020

### PR DESCRIPTION
**Pull request by quanah**
Fixes the help output for the actual usage of start_mining command

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
Could you make the commit message explicit instead of reference to an external website ?
Also, I think you should add something like "(default 1 thread)" after "Start mining for specified address, start_mining <addr> [<threads>]" since you lose the documented default.
Otherwise the patch is fine, thanks.

**Comment by quanah** [comment]
Sure :) I'll clean it up etc.

**Comment by quanah** [comment]
There doesn't seem to be anything consistent in how the descriptive text is done.  Closest I could find was set_log, which has
    , "set_log <level> - Change current log detalization level, <level> is a number 0-4"

Does
    , "Start mining for specified address, start_mining <addr> [<threads>], default 1 thread"

look ok to you?

**Comment by moneromooo-monero** [comment]
Yes, that is fine, thanks :)

**Comment by moneromooo-monero** [comment]
ok

**Pull request merged**
