### PR TITLE
simplewallet: default to max-concurrency 1 on MacOS X

### PR DESCRIPTION
**Pull request by moneromooo-monero**
A suspected bug in pthread/kernel, though might be that
I messed something up too...

This might rope in more platforms though.

### CODE REVIEW

**Comment by radfish** [comment]
I just observed a segfault on armv7h which was consistently reproducible (a few minutes after startup) and went away with max-concurrency=1.

**Comment by moneromooo-monero** [comment]
Oh, very interesting. Did you keep a stack trace (all threads) ?

**Comment by alexeicolin** [comment]
Unfortunately, no -- and I can't figure out why systemd-coredump is saving coredumps from other sevices but not for bitmonerod (WTF). I could reproduce the segfault again, however, then I ran inside GDB and it did not segfault, but completed the sync over several hours and kept running. So, no clues, unfortunately.

Sidenote: got a segfault on exit, saved a core for that (doesn't seem related, and I think there is a PR for exit segfault already)

**Comment by radfish** [comment]
(oops mixed up GH accounts)

Unfortunately, no -- and I can't figure out why systemd-coredump is saving coredumps from other sevices but not for  bitmonerod (WTF). I could reproduce the segfault again, however, then I ran inside GDB and it did not segfault, but completed the sync over several hours and kept running. So, no clues, unfortunately.                                        
                                                                                                                             
Sidenote: got a segfault on exit, saved a core for that (doesn't seem related, and I think there is a PR for exit segfault  already)

**Comment by moneromooo-monero** [comment]
The exit one is likely the data_logger one, which is known. If it's not, it'd be good to know. Otherwise, it can be ignored.

For the core, maybe /proc/sys/kernel/core_pattern is set to some pipe.

**Pull request merged**
