### PR TITLE
cmake: fix handling of ARCH var and readme edits to build instructions

### PR DESCRIPTION
**Pull request by radfish**
The first commit in the list below contains a fix to an issue I introduced earlier when fixing the native build on ARM. Another commit is a revert that brings back the release-static-arm* targets: it was wrong to delete them -- I misunderstood their purpose: they are not for bulding native binaries (-march=native) on ARM, which I fixed earlier to build  via normal 'make release', but for building generic binaries portable across the given ARM family for release to users. Could call it "light cross-compilation", where there is a constraint that host CPU arch must be compatible with target CPU arch. Same with the release-static-{32,64} targets and *-win{32,64} targets -- on Windows there is no "native" build at all, the only build for Windows is a cross-compilation.

For native builds, ARCH is not set (and defaults to 'native', so '-march=native'). For the "cross-comilation" builds, ARCH is set to the target architecture. There is also an option to set ARCH to "default" to not pass -march at all, but that is currently not used.

In the future, if/when cross-compilation from x86_64 to armv* is setup, we'll need another set of targets. At that point would either revise the naming convention or add logic to top-level makefile that would detect the host arch and do the right thing to build the specified target arch binary. For example, so that same make release-static-arm7 works if invoked either on an arm box or an x86_64 box.

Editted readme to hopefully make things clearer, shorter, and easier to follow. Link to the editted version without diff noise: https://github.com/radfish/bitmonero/tree/PR--cmake-arch-handling

commit c54b9a1a05fca44703e5a3359c2725d26ff60bc4
    cmake: don't set ARCH from CMAKE_SYSTEM_PROCESSOR
    
    It is not correct to do so, because ARCH should only take values
    supported by the -march argument, with the exception of 'default'
    which denotes not passing -march at all.
    
    ARCH defines the target architecture for builds that are intended to be
    portable to other machines.

commit a0d40587ea0b7bdc4084bcd7727d876948d30d7d
    Revert "makefile: remove unnecessary ARM-specific targets"
    
    This reverts commit ecd0f2dde7b2d8f3ff820d1190c00401c436384a.
    
    These targets that are not native builds. They are for builds
    portable within processors of a given family.
    
    'make release' used to not work to build a native build on ARM, but that
    has been fixed. These targets are unrelated to the native build.

commit c2bc34b7366e9f5dcb62603bf3ac79b88357c2b0
    Revert "Interpret x86_64 as x86-64 for architecture"
    
    This reverts commit 86234921506944dddab4e2f5edf96bf747be6c73.
    
    Let's restrict ARCH to values accepted by -march to keep things clear
    and consistent. ARCH is -march, with only one exception: a value of
    "default" indicates to not pass -march at all.

commit 43c07a1cfa4799921f507b4afbbca9fdd7a781ea
    readme: editted install/build instructions for clarity
    
    * some re-org of sections to make things more concise
    * dedicated section for installing from packages vs building from source
    * for Windows, instruct to run the top-level makefile targets,
      because I don't see any reason not to -- advanced users
      will look into the makefile and find the cmake command there
      if they need to.
    * for Windows, instruct to install *-toolchain meta package
      which includes expat
    * added some context info here and there to aid -- I tried
      to clarify things that confused me, e.g. Windows build is
      cross-compilation to be precise; motivation for targets
      that are meant for generating portable binaries as opposed
      to binaries optimized to host CPU.

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok, though the x86-64 thing was because it was confusing since x86_64 is canonical.

**Comment by radfish** [comment]
Yeah, I was uneasy reverting, but all other settings of ARCH are according to the choices in 'man gcc' (like, armv7-a, etc) which don't really have any corresponding identifier in other contexts like x86-64 does. So, I simplified for consistency sake.

**Comment by radfish** [comment]
@monero-project sorry to pile stuff after your review; static build failed on ARM due to libunwind so pushed a fix for that.

**Comment by fluffypony** [comment]
reviewed

**Pull request merged**
