### PR TITLE
Show correct amount of days behind/ahead while syncing

### PR DESCRIPTION
**Pull request by tobiasw2**
Fix for issue #591
sync status message in daemon is using v1 block time

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
It doesn't fix it, it just changes the range where it's wrong :P
It should really use V1 and V2 block times for various ranges based on the matching hard fork starting heights.
Also, your PR includes two irrelevant merge patches. You should rebase with something like: git rebase master (when currently in your branch).

**Comment by tobiasw2** [comment]
Ok I got it. Shame on me :(
Thanks for the feedback - I will have another look :)

**Comment by moneromooo-monero** [comment]
Thanks, there's only two cases so it shouldn't be too much of a pain.

**Comment by tobiasw2** [comment]
So I understood what my mistake was and fixed it. I already tested it with my node and pushed a new commit. The only thing that is bugging me and that I just couldn't avoid is hard coding the block height where v2 was forked into my code. I found a place where this information already exists (Blockchain class) but wasn't able to access it (without further changes). Would be really nice to get some feedback on this. Sorry if I'm causing trouble but I'm still getting used to the codebase :(

**Comment by moneromooo-monero** [comment]
That seems OK. Hardcoding the v2 height isn't ideal, but it's OK to leave it that way since I don't think it can be accessed from there. It can always be changed later.
The only thing left is that you've got 4 commits: a wrong one, the fix on top, and two merges with irrelevant diffs. Please rebase to master, and squash the two "real" commits together, and then it's good to go.
Thanks

**Comment by tobiasw2** [comment]
I cleaned up the pull request (only one commit left). Sorry for that.
I hope it is fine now.
Thanks for your help!

**Pull request merged**
