### PR TITLE
Threadpool fix for single core and MINGW duplicate library fix

### PR DESCRIPTION
**Pull request by NoodleDoodleNoodleDoodleNoodleDoodleNoo**

### CODE REVIEW

**Comment by tewinget** [comment]
I assume the cmake bit is correct (cursory glance, on my phone).

Is the cpp change intended to address the case where threads == 1?  It
seems like it will not have any effect, but I'm not sure.

**Comment by NoodleDoodleNoodleDoodleNoodleDoodleNoo** [comment]
For MINGW:
The registry location is not consistent across all windows platforms. Sometimes it exists on the original codes' specified registry location, other times it is under a UID key. When the call fails it returns "/registry" instead of something similar to "C:/mingw64" or "C:/mingw32".

For the threadpool:
It has the effect of not launching the threadpool since you need a minimum of 2 threads to use it. Without this condition, it creates a thread for the pool, starts the i/o service and idle worker, but the worker, i/o service and pool are never properly terminated since KILL_IO_SERVICE() is only processed when threads > 1.  (https://github.com/NoodleDoodleNoodleDoodleNoodleDoodleNoo/bitmonero/blob/70ae2ee711c8262f5aba9ebe81f7b5b49bc26e6b/src/cryptonote_core/blockchain.cpp#L2020)

**Comment by tewinget** [comment]
Ah okay, I read it a bit wrong.  That said, I don't think a thread pool of
one should be handled as a special case.

**Comment by NoodleDoodleNoodleDoodleNoodleDoodleNoo** [comment]
While we can certainly allow the threadpool to be launched when there is only a single thread, there is no point in doing this as it offers no gains and essentially does nothing but use up resources.

**Pull request merged**
