### PR TITLE
Two CMake fixes for clang

### PR DESCRIPTION
**Pull request by fluffypony**
1. cleans up the dual clang if-then blocks
2. fixes the atomic check, which will fail on gcc Linux builds

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok

**Comment by radfish** [comment]
I only tested the gcc build on i686 with Arch (gcc 6.1.1).  There's a /usr/lib/libatomic.so on the system owned by gcc-libs package. So, this issue is either a 32-bit vs 64-bit or older system (14.04) vs newer system.

**Comment by fluffypony** [comment]
@radfish just to check - if it's not needed for the gcc build at all we can leave it out, right?

**Comment by radfish** [comment]
Yeah, so far it has not been needed by any gcc build. (I just tried to save one more conditional branch in cmake, given that build with libatomic succeeded on my the system, but now we know that it fails on other systems.)

**Pull request merged**
