### PR TITLE
cmake: coverage option

### PR DESCRIPTION
**Pull request by radfish**
Make coverage completely optional.

Also, let's see if this ARGS works for excluding tests.

### CODE REVIEW

**Comment by ranok** [comment]
Looks good as long as the travis build completes

**Comment by fluffypony** [comment]
Please rebase :)

**Comment by radfish** [comment]
rebased; @fluffypony just to make sure my merging didn't break things, let's wait for travis's approval on this one.

**Comment by fluffypony** [comment]
Ok cool, it's passed, so merging

**Pull request merged**
