### PR TITLE
Fix Issue #807

### PR DESCRIPTION
**Pull request by hyc**
Broken by 48d0747d005c80fde3837fc4bcdb3eff26907d74

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
While this makes it compile, it will cause the transfer to fail, and the test too most likely.
I can look at how to fix maybe tomorrow if needed.

**Comment by moneromooo-monero** [comment]
Granted, that test isn't actually run anyway...

**Comment by moneromooo-monero** [comment]
I think this is a better fix: https://github.com/monero-project/bitmonero/pull/811

**Comment by hyc** [comment]
Sounds fine to me, closing this then.

**Pull request closed without merging**
