### PR TITLE
blockchain_db: store key images for tx without outputs too

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by iamsmooth** [comment]
Yes and let people who are currently testing the db version know to upgrade once merged

**Comment by iamsmooth** [comment]
Also, we will need either a db fix tool or people will have to re-import. I vote for re-import but I don't have a strong feeling on it.

**Comment by luigi1111** [comment]
Will there be anything to "fix" if no offending txs have occurred?

**Comment by fluffypony** [comment]
@luigi1111 yes - you'll want to sync up from scratch or reimport

**Comment by luigi1111** [comment]
Building now. Might as well test what happens if I don't (unless someone has tested it already?).

**Comment by iamsmooth** [comment]
export then import should work

**Pull request merged**
