### PR TITLE
readme: organize deps into table

### PR DESCRIPTION
**Pull request by radfish**
Anyone know if ldns, BDB, expat are current?

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
ok. Optional change to make versions like >=X.Y instead of X.Y, but I think it's clear enough if not.

**Comment by radfish** [comment]
Changed column title to "Min. Version." Hopefully this achieves same purpose.

**Comment by fluffypony** [comment]
Please rebase :)

**Comment by radfish** [comment]
rebased

**Pull request merged**
