### PR TITLE
tx_pool: ensure no txes that fail check_inputs get in the block template

### PR DESCRIPTION
**Pull request by moneromooo-monero**

### CODE REVIEW

**Comment by iamsmooth** [comment]
Reviewed. This looks like a good fix given the way the tx pool currently operates.

**Comment by iamsmooth** [comment]
One question. Could this short-circuit the check anyway?

https://github.com/monero-project/bitmonero/blob/master/src/cryptonote_core/blockchain.cpp#L2079

**Comment by iamsmooth** [comment]
#792

**Comment by moneromooo-monero** [comment]
As discussed on IRC, I agree this probably needs removing. I'm waiting on NoodleDoodle to comment first.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/800

**Comment by NoodleDoodleNoodleDoodleNoodleDoodleNoo** [comment]
This behaviour is indeed wrong. It should never bypass the check when public check_tx_inputs(..) is called. The only time it should check the check_tx_inputs_table is when private check_tx_inputs(..) is called (as in the case of handle_block_to_main_chain(..). You can probably remove it or just flag it to skip by default and only use it with handle_block_to_main_chain(..)

**Comment by fluffypony** [comment]
Does this mean that we're closing this in favour of #800?

**Comment by iamsmooth** [comment]
both are needed

**Pull request merged**
