### PR TITLE
2014 network limit 1.0a +utils +toc -doc -drmonero

### PR DESCRIPTION
**Pull request by rfree**
Network limiting works, quite well in this version. 
More work (and polishing!) is waiting in pipeline, how ever this should be merged as first step to avoid huge unmanageable diffs.
Some code (otshellutils contributed lib) will be reduced later on but no harm in taking this all as it is right now.

Please test on Windows and Mac OS X a bit before releasing.

commands and options for network limiting
works very well e.g. for 50 KiB/sec up and down
ToS (QoS) flag
peer number limit
TODO some spikes in ingress/download
TODO problems when other up and down limit
added "otshell utils" - simple logging (with colors, text files channels)

### CODE REVIEW

**Comment by rfree** [comment]
Commit is GPG signed.
GPG keys are confirmed in our longest project (from 2013) - Mempo, here:

https://github.com/mempo/deterministic-kernel/blob/master/doc/build.txt

public keys are also in https://github.com/mempo/deterministic-kernel/blob/master/doc/

**Comment by fluffypony** [comment]
Thanks rfree! Quick question: in .gitignore, why have you added ```miniupnpcstrings.h``` and ```version/```?

**Comment by rfree** [comment]
These files are generated by cmake && make, so same as .o objects they should not be committed into git.

**Comment by fluffypony** [comment]
Fails to build on OS X:

```
[  4%] Building CXX object contrib/otshell_utils/CMakeFiles/otshell_utils.dir/utils.cpp.o
/Users/ric/Desktop/working/bitmonero/contrib/otshell_utils/utils.cpp:88:13: error: no member named
      'to_time_t' in 'std::__1::chrono::steady_clock'; did you mean
      'std::chrono::system_clock::to_time_t'?
        time_now = std::chrono::high_resolution_clock::to_time_t(now);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   std::chrono::system_clock::to_time_t
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:925:23: note: 
      'std::chrono::system_clock::to_time_t' declared here
    static time_t     to_time_t  (const time_point& __t) _NOEXCEPT;
                      ^
/Users/ric/Desktop/working/bitmonero/contrib/otshell_utils/utils.cpp:88:59: error: no viable conversion
      from 'time_point<class std::__1::chrono::steady_clock, duration<[...], ratio<[...],
      1000000000>>>' to 'const time_point<class std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>'
        time_now = std::chrono::high_resolution_clock::to_time_t(now);
                                                                 ^~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: 
      candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'std::chrono::high_resolution_clock::time_point' (aka 'time_point<std::__1::chrono::steady_clock,
      duration>') to 'const std::__1::chrono::time_point<std::__1::chrono::system_clock,
      std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000> > > &' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: 
      candidate constructor (the implicit move constructor) not viable: no known conversion from
      'std::chrono::high_resolution_clock::time_point' (aka 'time_point<std::__1::chrono::steady_clock,
      duration>') to 'std::__1::chrono::time_point<std::__1::chrono::system_clock,
      std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000> > > &&' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:769:5: note: 
      candidate template ignored: could not match 'std::__1::chrono::system_clock' against
      'std::__1::chrono::steady_clock'
    time_point(const time_point<clock, _Duration2>& t,
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:925:53: note: 
      passing argument to parameter '__t' here
    static time_t     to_time_t  (const time_point& __t) _NOEXCEPT;
                                                    ^
2 errors generated.
make[3]: *** [contrib/otshell_utils/CMakeFiles/otshell_utils.dir/utils.cpp.o] Error 1
make[2]: *** [contrib/otshell_utils/CMakeFiles/otshell_utils.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all-release] Error 2
```

**Comment by fluffypony** [comment]
Ubuntu builds, but complains about this a bunch of times:

```
In file included from /root/bitmonero/contrib/epee/include/net/abstract_tcp_server2.h:295:0,
                 from /root/bitmonero/contrib/epee/include/net/levin_server_cp2.h:32,
                 from /root/bitmonero/src/p2p/net_node.h:48,
                 from /root/bitmonero/tests/core_proxy/core_proxy.cpp:48:
/root/bitmonero/contrib/epee/include/net/abstract_tcp_server2.inl: In instantiation of 'bool epee::net_utils::connection<t_protocol_handler>::do_send(const void*, size_t) [with t_protocol_handler = epee::levin::async_protocol_handler<nodetool::p2p_connection_context_t<cryptonote::cryptonote_connection_context> >; size_t = long unsigned int]':
/root/bitmonero/tests/core_proxy/core_proxy.cpp:278:1:   required from here
/root/bitmonero/contrib/epee/include/net/abstract_tcp_server2.inl:328:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (allow_split && (cb > chunksize_max)) {
                          ^
In file included from /root/bitmonero/contrib/epee/include/net/abstract_tcp_server2.h:58:0,
                 from /root/bitmonero/contrib/epee/include/net/levin_server_cp2.h:32,
                 from /root/bitmonero/src/p2p/net_node.h:48,
                 from /root/bitmonero/tests/core_proxy/core_proxy.cpp:48:
/root/bitmonero/contrib/epee/include/net/abstract_tcp_server2.inl:351:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
      ASRT(len>0); ASRT(len < std::numeric_limits<size_t>::max());   // yeap we want strong < then max size, to be sure
                            ^
/root/bitmonero/contrib/epee/include/net/../../../../contrib/otshell_utils/utils.hpp:297:28: note: in definition of macro 'ASRT'
 #define ASRT(x) do { if (!(x)) nOT::nUtils::Assert(false, OT_CODE_STAMP, #x); } while(0)
                            ^
```

**Comment by fluffypony** [comment]
Haven't tested Windows yet as my VM is having issues, will test on Windows after the PR is updated.

**Comment by rfree2** [comment]
Thanks, working on it

**Comment by rfree2monero** [comment]
Starting new PR with fixed above problem, lots of other fixes, better debugged (valgrid, debian, ubuntu, parts of code also on FreeBSD, on windows) in a moment

**Comment by rfree2monero** [comment]
https://github.com/rfree2monero/bitmonero/commits/work

e.g. https://github.com/rfree2monero/bitmonero/commit/f79821ac7ebc269b18dd2edd8ac0cb022861ad11

is the improved version.

Will sign it later. I recommend that few people should test it before merge with main. Also, there still remains the open problem in master regarding locking, that is more visbile when network threads sleep due to speed limiting.

**Pull request closed without merging**
