### PR TITLE
cmake, common/stack_trace.cpp: fix Clang build (should also fix build on OSX)

### PR DESCRIPTION
**Pull request by radfish**
*NOTE*: please keep commits separate when merging (no squash).

 common: stack trace: make clang happy with func ptrs

Tested that it builds with:
gcc 6.1.1, STATIC=OFF,i686
gcc 6.1.1, STATIC=OFF,armv7h
clang 3.8, STATIC=OFF,i686
clang 3.8, STATIC=OFF,armv7h

gcc 6.1.1, STATIC=ON,i686
clang 3.8, STATIC=ON,i686

Also tested that stack trace is generated fine on exception on:
i686, gcc 6.1.1, STATIC=OFF
(didn't bother testing all the other platforms/configs)

This should fix the build problem on OSX (#871, #901), but
I don't have OSX, so I could only test Clang on Linux.

 cmake: do not pass -stdlib=c++ to clang >=3.7

Tested on Linux (Arch) with clang 3.7 and 3.8 i686 and ARM:
if -stdlib=c++ is passed to clang, then the build errors
out with <string>,<iostrea>,etc. headers not found. Simply
not passing the arg fixes the problem.

**NOTE**: I just noticed that on OSX Clang identifies as "Apple Clang 7.3....", so (1) comparing Clang version might be problematic, and (2) maybe on OSX all versions of Clang need '-stdlib=c++', I have no way of knowing -- someone on OSX, please try and build it, so that we can fix the logic in cmake accordingly.

 cmake: include -ldl via cmake built-in var

This does two things:
1. fixes clang build, which otherwise errors with undefined symbol
'dlsym'.
2. simplifies the cmake script, delegating to cmake to figure
   out platform-specific flags for linking against the dl library.

 cmake: link with -latomic for clang

otherwise clang build fails with

../cryptonote_core/libcryptonote_core.a(miner.cpp.o): In function
`std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/bin/../lib/gcc/i686-pc-linux-gnu/6.1.1/../../../../include/c++/6.1.1/bits/atomic_base.h:396:
undefined reference to `__atomic_load_8'

This has no effect on the gcc build.

The one strange thing is that test code like

std::atomic<int> x;
int main() { return x; }

compiles and links without errors with clang, without -latomic.  This
alone would suggest that this patch is unnecessary, but that is not the
case. It's not clear exactly why, though. The bitmonero code is
including the same header, but it must be doing something more complex
than in this test code snippet that causes the failure at link time
pasted above. In any case, passing -latomic fixes the problem and
seems safe.

 cmake: ARM: clang: make warning non-fatal: inline asm

Clang issues a warning for some inline asm in stack_trace.cpp.  This
patch ieaves the warning to be displayed as a reminder to fix
the code.

### CODE REVIEW

**Comment by antanst** [comment]
I checked out this branch on OSX. When making `release`, CMake fails early with the following error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ATOMIC
    linked by target "common" in directory /Users/antonis/cryptos/bitmonero-radfish/src/common
    linked by target "cryptonote_core" in directory /Users/antonis/cryptos/bitmonero-radfish/src/cryptonote_core
    linked by target "blockchain_db" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_db
    linked by target "rpc" in directory /Users/antonis/cryptos/bitmonero-radfish/src/rpc
    linked by target "wallet" in directory /Users/antonis/cryptos/bitmonero-radfish/src/wallet
    linked by target "simpleminer" in directory /Users/antonis/cryptos/bitmonero-radfish/src/miner
    linked by target "simpleminer" in directory /Users/antonis/cryptos/bitmonero-radfish/src/miner
    linked by target "simplewallet" in directory /Users/antonis/cryptos/bitmonero-radfish/src/simplewallet
    linked by target "simplewallet" in directory /Users/antonis/cryptos/bitmonero-radfish/src/simplewallet
    linked by target "daemonizer" in directory /Users/antonis/cryptos/bitmonero-radfish/src/daemonizer
    linked by target "daemon" in directory /Users/antonis/cryptos/bitmonero-radfish/src/daemon
    linked by target "daemon" in directory /Users/antonis/cryptos/bitmonero-radfish/src/daemon
    linked by target "cn_deserialize" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_utilities
    linked by target "blockchain_dump" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_utilities
    linked by target "blockchain_export" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_utilities
    linked by target "blockchain_import" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_utilities
    linked by target "blockchain_converter" in directory /Users/antonis/cryptos/bitmonero-radfish/src/blockchain_utilities

-- Configuring incomplete, errors occurred!
See also "/Users/antonis/cryptos/bitmonero-radfish/build/release/CMakeFiles/CMakeOutput.log".
See also "/Users/antonis/cryptos/bitmonero-radfish/build/release/CMakeFiles/CMakeError.log".
make: *** [cmake-release] Error 1

**Comment by moneromooo-monero** [comment]
What is the warning given for asm in stack_trace.cpp ?

The link error for atomic stuff is probably because an 8 byte value needs a call, while 4 byte is inline.

Looks ok.

**Comment by radfish** [comment]
> What is the warning given for asm in stack_trace.cpp ?

```[ 35%] Building CXX object src/common/CMakeFiles/common.dir/stack_trace.cpp.o
/home/redfish/dev/bitmonero/src/common/stack_trace.cpp:111:7: warning: use of SP or PC in the list is deprecated [-Winline-asm]
  if (unw_getcontext(&ctx) < 0) {
      ^
/usr/include/libunwind-common.h:108:29: note: expanded from macro 'unw_getcontext'
#define unw_getcontext(uc)              unw_tdep_getcontext(uc)
                                        ^
/usr/include/libunwind-arm.h:270:5: note: expanded from macro 'unw_tdep_getcontext'
    "stmia %[base], {r0-r15}"                                           \
    ^
<inline asm>:1:2: note: instantiated into assembly here
        stmia r0, {r0-r15}
        ^
1 warning generated.
```

@antanst Please fetch the additional commit and try now. Thanks for helping with this!

**Comment by antanst** [comment]
Compiles fine now. Thanks!

**Comment by schnerchi** [comment]
Can confirm. Compiles now.

Thanks!

**Comment by fluffypony** [comment]
reviewed

**Pull request merged**
