### PR TITLE
Several minor patches needed to compile on armv7h with gcc 6.1.1

### PR DESCRIPTION
**Pull request by radfish**
The compiler treated some warnings as errors, so fixed those.

The compiler complained about exceptions thrown from destructors. The commits in this PR add `noexcept(false)` specs to these destructors, but perhaps another fix would be to avoid throws (most or all of which seem to be non-essential logging/error-handling code).

NOTE: I regenerated the makefile with cmake so some compiler flag came from system (mostly default makepkg.conf). Btw, might be good to remove generated Makefiles from VCS.

### CODE REVIEW

**Comment by iamsmooth** [comment]
Unlike the other PR, this one has quite a few changes so better make sure all of these still compile properly with all the older compilers people use.

**Comment by iamsmooth** [comment]
@othe also raised the question in IRC whether oaes_lib should be modified, I guess since that comes from somewhere and better to leave crypto libraries we didn't create unchanged.

**Comment by moneroexamples** [comment]
Cool. I was just about to push `noexcept(false)` commit myself. Will check if all your changes compile on Arch soon.

**Comment by radfish** [comment]
@moneroexamples Cherry-picked your indentation fix. Probably it didn't fail for me because this code is not used for ARM (hypothesis, didn't check). I am also on Arch, btw.

@iamsmooth @othe Agreed. I am no fan of even vendoring dependencies, much less forking them. I contained those changes into a separate commit, so that it can be reverted easily as soon as upstream applies the fix. You can't drop this commit from this patch set, but it won't build, so I think it is reasonable to temporarily form, given that the change is nothing more than noexcept(false) specs, which (I believe) is for a compile-time check only and doesn't even affect the resulting binary.

@monexamples @cryptovision Crazy how the two pull requests crossed by one hour. We must have been literally commiting at the same time.

**Comment by moneroexamples** [comment]
@radfish 
It compiles now with the cherry-picked commit from by PR.

Was working on the same issues as you on arch (except arm cpu). Arch just recently upgraded gcc to 6.1, and  many programs started to fail to compile. I guess many ppl are working on these issues now for different programs.

**Comment by moneromooo-monero** [comment]
Throwing dtors seems iffy to me. If it's not too much bother, since you say it's logging, I'd catch/log instead.

**Pull request merged**
