### PR TITLE
libwallet public api (in progress)

### PR DESCRIPTION
**Pull request by mbg033**
not sure if I placed tests for libwallet_api to the right place (tests/libwallet_api_tests) - please correct me if I'm wrong

### CODE REVIEW

**Comment by fluffypony** [comment]
Hi Ilya, thanks for submitting a PR, and excellent work! Two things that jump out at me:

1. There are a bunch of merge conflicts, you're going to have to rebase this PR for it to be merge-able
2.  Just at a quick glance I see there are changes to the 64-bit Windows CMake toolchain, can you explain why those changes were made? I just want to find out if they should be made permanently or not:)

Thanks again!

**Comment by mbg033** [comment]
Hi Riccardo,
sorry for the conflicts, I just rebased PR; 

As for changes for x64 CMake toolchain - that's weird, but I was unable to build it under Windows x64 (msys2) without that changes - build has failed with CMAKE_LINKER-NOTFOUND. Right now I booted to Windows and tried to represent issue with approximately same commit and with 'release-static-win64' target - but I couldn't - build finished successfully. Not really sure why that issue happened first time, I only remember I updated my msys2 installation recently.  Anyway,  I removed these commits from the PR now.

**Comment by mbg033** [comment]
Noticed that "tests/crypto" failed to build currently (Ubuntu), so I added boost::system to it's CMakeLists.txt

**Comment by moneromooo-monero** [comment]
What is the intent of this new class ? It seems like the start of a thin layer above wallet2. Why have another API that's different for the same thing, instead of modifying wallet2 if it doesn't lend itself well to your use ?

Also, the store_to function essentially copy/pastes the logic one in wallet2, I'm not sure it's a good idea to duplicate all of wallet2 that way (assuming you intend to continue).

Alternatively, there may be a good argument for doing so, what is it ?

**Comment by mbg033** [comment]
Yes, idea was  a) to provide interface to wallet2 functionality for gui app without any templates and other compile-time dependencies except STL and b) to keep simplewallet app working so it doesn't need to be modified at the same.
wallet2::store_to - yes, I agree this is a DRY violation currently, it's marked as TODO in source code.

**Comment by fluffypony** [comment]
Ok so then I would suggest we aim at deprecating wallet2 later on in favour of this new API, so please try keep it as flexible and well documented as possible:)

**Pull request merged**
